{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rick-api.fullname" . }}
  labels:
    {{- include "rick-api.labels" . | nindent 4 }}
    {{- include "rick-api.chartLabels" . | nindent 4 }}
    annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "rick-api.fullname" . }}
                port:
                  number: {{ .Values.service.port }}

{{- end }}