apiVersion: v1
kind: Service
metadata:
  name: {{ include "rick-api.fullname" . }}
  labels:
    {{- include "rick-api.labels" . | nindent 4 }}
    {{- include "rick-api.chartLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "rick-api.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}